$('./div[@id="bottom-5"]'){
				insert_at('top','span',class:'sprites-Stiched-pattern-copy',style:'display:block;margin:15px 0px')
				$('./div/div'){
					insert('span',class:'mw-divider')
				}
				$('./div/div/div[@id="footerModule2"]/ul/li'){

					match(index()){
						with(1){
							$('./a'){
								add_class('sprites-Layer-facebook')
								text(){
									set('')
								}
							}
						}
						with(2){
							$('./a'){
								add_class('sprites-Layer-twitter')
								text(){
									set('')
								}
							}
						}
						with(3){
							$('./a'){
								add_class('sprites-Layer-pinterest')
								text(){
									set('')
								}
							}
						}
						with(4){
							$('./a'){
								add_class('sprites-Layer-blogger')
								text(){
									set('')
								}
							}
						}
						with(5){
							$('./a'){
								add_class('mw-hide')
								text(){
									set('')
								}
							}
						}
						else(){
							$('./a'){
								add_class('sprites-Layer-youtube')
								text(){
									set('')
								}
							}
						}
					}
				}
				
			}